### ISSUE TITLE
TODO?

### ISSUE THREAD

**Issue by ikornaselur** [DeadpoolAndObjectOrientedProgramming/awesome-game#3]
#### Important
- [ ] Ball collision angle to paddle (see #2)
- [ ] Ball collision to bricks (see #2)
#### Normal priority
- [ ] Lives
- [ ] Ball speed change when colliding with paddle (see #2)
#### Nice to have
- [ ] Scoring/Points
- [ ] Powerups
  - Faster/slower ball
  - Bigger/smaller paddle
  - "Guns" 
#### Ideas?
- [ ] Splash screen on load? 
- [ ] "You win" screen?

_Feel free to edit this issue with more points_
